version: 2

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - builder: rust
    flags:
      - --release
      - --package=evmqtt-rs
    targets:
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}-{{ .Arch }}

dockers_v2:
  - id: evmqtt-rs
    images:
      - "ghcr.io/bdolgov/evmqtt-rs-haos"
    tags:
      - "{{ .Version }}"
      - "latest"
    platforms:
      - "linux/amd64"
      - "linux/arm64"
    dockerfile: haos_app/Dockerfile
    extra_files:
      - haos_app/run.sh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
