version: 2

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - builder: rust
    flags:
      - --release
      - --package=evmqtt-rs
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-gnu
      - aarch64-unknown-linux-musl

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}-{{ .Target }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
